### ISSUE TITLE
commonlands converter (line 11)

### ISSUE THREAD

**Issue by xackery** [daeken/OpenEQ#37] opened 2016-10-15 11:48 UTC
Traceback (most recent call last):
  File "converter.py", line 64, in <module>
    main(*sys.argv[1:])
  File "converter.py", line 56, in main
    convertNew(name)
  File "converter.py", line 45, in convertNew
    readZon(zfiles['%s.zon' % name], zone, zfiles)
  File "D:\code\eqemu\openeq\converter\zon.py", line 11, in readZon
    assert b.read(4) == 'EQGZ'
AssertionError

**Comment by daeken** [comment] 2016-10-19 09:52
Dupe of #27

**Closed as completed** 2016-10-19 09:52 UTC
